import 'dart:convert';
import 'package:cat_trader/src/models/cat.dart';

class DummyData {
  static List<Cat> cats = [];
  static List<dynamic> breeds = jsonDecode('breeds.json');
  static List<String> catNames = [
    'Mr. Whiskers',
    'Sir Purrs-a-Lot',
    'Princess Paws',
    'Captain Cuddles',
    'Whiskerface',
    'Mittens McFluff',
    'Admiral Snuggles',
    'Purrlock Holmes',
    'Furbert Einstein',
    'Duchess Fluffington',
    'Baron von Purr',
    'Sir Fluffykins',
    'Whisker Doodle',
    'Lady Whiskerella',
    'Countess Purrsia',
    'Mr. Fuzzbutt',
    'Whisker McSnuggles',
    'Dr. Purrfect',
    'Furrnando',
    'Snugglebug',
    'Pudding Paws',
    'Cuddle Muffin',
    'Button Nose',
    'Purrsnickety',
    'Sir Wigglepaws',
    'Miss Fluffytoes',
    'Mr. Fuzzypants',
    'Captain Whiskerbeard',
    'Purrcival',
    'Lord Meowington',
    'Whisker McWhiskers',
    'Sir Snugglepuss',
    'Whisker Biscuit',
    'Fuzz Aldrin',
    'Purrlock Felines',
    'Furball McGraw',
    'Whisker Lickins',
    'Whiskerjinks',
    'Miss Purrfect',
    'Mr. Fluffernutter',
    'Princess Purrl',
    'Fluffernutter',
    'Purrito',
    'Cuddle Puff',
    'Sir Meow-a-Lot',
    'Lady Fluffikins',
    'Mr. Wiggletail',
    'Count Fluffula',
    'Purrcy',
    'Whisker Waffle'
  ];
}
